git submodule add git@github.com:pcdshub/lcls-plc-crixs-motion
git submodule add git@github.com:pcdshub/lcls-plc-crixs-vac
git submodule add git@github.com:pcdshub/lcls-plc-kfe-gmd-vac
git submodule add git@github.com:pcdshub/lcls-plc-kfe-motion
git submodule add git@github.com:pcdshub/lcls-plc-kfe-rix-motion
git submodule add git@github.com:pcdshub/lcls-plc-kfe-rix-vac
git submodule add git@github.com:pcdshub/lcls-plc-kfe-vac
git submodule add git@github.com:pcdshub/lcls-plc-kfe-xgmd-vac
git submodule add git@github.com:pcdshub/lcls-plc-lamp-vac
git submodule add git@github.com:pcdshub/lcls-plc-lfe-motion
git submodule add git@github.com:pcdshub/lcls-plc-lfe-vac
git submodule add git@github.com:pcdshub/lcls-plc-tmo-motion
git submodule add git@github.com:pcdshub/lcls-plc-tmo-vac
git submodule add git@github.com:pcdshub/lcls-plc-vls-vac
git submodule add git@github.com:pcdshub/lcls-plc-vonhamos-motion
git submodule add git@github.com:pcdshub/lcls-twincat-motion
